---
title: "Portfolio"
author: "Niels Rouws"
date: "2/10/2021"
output: html_document
---

```{r}

library(tidyverse)
library(spotifyr)

```

```{r}
rock60s <- get_playlist_audio_features("", "37i9dQZF1DWWzBc3TOlaAV")
rock70s <- get_playlist_audio_features("", "37i9dQZF1DWWwzidNQX6jx")
rock80s <- get_playlist_audio_features("", "37i9dQZF1DX1spT6G94GFC")
rock90s <- get_playlist_audio_features("", "37i9dQZF1DX1rVvRgjX59F")
rock00s <- get_playlist_audio_features("", "37i9dQZF1DX3oM43CtKnRV")
rock10s <- get_playlist_audio_features("", "37i9dQZF1DX99DRG9N39X3")


rock <-
  bind_rows(
    rock60s %>% mutate(category = "1960s"),
    rock70s %>% mutate(category = "1970s"),
    rock80s %>% mutate(category = "1980s"),
    rock90s %>% mutate(category = "1990s"),
    rock00s %>% mutate(category = "2000s"),
    rock10s %>% mutate(category = "2010s")
  ) %>%
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  )

```

```{r}
ggplot(
  rock,
  aes(
    x = category
  )
) +
  geom_bar() + 
  labs(
    title = "Amount of songs in the playlist per decennium"
  )

```
```{r}

ggplot(
  rock,
  aes(
    x = category,
    y = acousticness, 
    fill = mode
  )
) +
  geom_boxplot(
    position = position_dodge(width = 0.5),
    outlier.alpha = 0.6,
  ) +
  theme(legend.position = c(0.9, 0.9)) +
  labs(title = " Distribution of acousticness per decennia per mode")

```
```{r}
ggplot(
  rock,
  aes(
    x = category,
    y = valence, 
    fill = mode
  )
) +
  geom_boxplot(
    position = position_dodge(width = 0.5),
    outlier.alpha = 0.6,
  ) +
  theme(legend.position = c(0.9, 0.9)) +
  labs(title = "Distribution of valence per decennia per mode")
```



```{r}
ggplot(
  rock,
  aes(
    x = loudness,
    y = energy,
    color = category
  )
) +
  geom_smooth(method = "loess", formula = "y ~ x") + 
  geom_point(alpha = 0.4) +
  facet_wrap(~category) +
  labs(
    title = "Energy related to tempo per decennium."
  )
```

